// <auto-generated />
using API.UTRG.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace API.UTRG.Migrations
{
    [DbContext(typeof(AlumnoInfoDbContext))]
    partial class AlumnoInfoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.UTRG.Entities.Alumno", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Telefono")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("API.UTRG.Entities.RedSocials", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlumnoId");

                    b.Property<string>("Migracion");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<string>("RedSocial");

                    b.HasKey("ID");

                    b.HasIndex("AlumnoId");

                    b.ToTable("RedSocials");
                });

            modelBuilder.Entity("API.UTRG.Entities.RedSocials", b =>
                {
                    b.HasOne("API.UTRG.Entities.Alumno", "Alumno")
                        .WithMany("Redes")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
